// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlhqI0G3u2Y-6GOIungl86ZydVeINfqnc',
    appId: '1:270495108550:web:76230b7edd9568d92e36c7',
    messagingSenderId: '270495108550',
    projectId: 'todo-flutter-41948',
    authDomain: 'todo-flutter-41948.firebaseapp.com',
    storageBucket: 'todo-flutter-41948.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMhzXKWIc03NN__CcQ-EqeR536c1pr0R4',
    appId: '1:270495108550:android:bce7f8df4ccb6f992e36c7',
    messagingSenderId: '270495108550',
    projectId: 'todo-flutter-41948',
    storageBucket: 'todo-flutter-41948.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjdTALYpiW29RjW1eJz5QhHvoV6q2t9eo',
    appId: '1:270495108550:ios:511a0e1d29a68a842e36c7',
    messagingSenderId: '270495108550',
    projectId: 'todo-flutter-41948',
    storageBucket: 'todo-flutter-41948.firebasestorage.app',
    androidClientId: '270495108550-thjg1ddv7jb6pc68gaillpgegs57gvou.apps.googleusercontent.com',
    iosClientId: '270495108550-palqe1ie0cmfjnfkmsh8qkpi1bfekohm.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjdTALYpiW29RjW1eJz5QhHvoV6q2t9eo',
    appId: '1:270495108550:ios:511a0e1d29a68a842e36c7',
    messagingSenderId: '270495108550',
    projectId: 'todo-flutter-41948',
    storageBucket: 'todo-flutter-41948.firebasestorage.app',
    androidClientId: '270495108550-thjg1ddv7jb6pc68gaillpgegs57gvou.apps.googleusercontent.com',
    iosClientId: '270495108550-palqe1ie0cmfjnfkmsh8qkpi1bfekohm.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlhqI0G3u2Y-6GOIungl86ZydVeINfqnc',
    appId: '1:270495108550:web:9ea86cfc12b17dc62e36c7',
    messagingSenderId: '270495108550',
    projectId: 'todo-flutter-41948',
    authDomain: 'todo-flutter-41948.firebaseapp.com',
    storageBucket: 'todo-flutter-41948.firebasestorage.app',
  );

}